### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by franciscolourenco** [Stuk/sublime-edit-history#2]
Previous edit point throws this:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 350, in run_
    return self.run(edit)
  File "./Edit History.py", line 153, in run
  File "./Edit History.py", line 50, in back
  File "./Edit History.py", line 40, in _set_next
TypeError: No registered converter was able to produce a C++ rvalue of type SelectionRegion from this Python object of type NoneType
```

Next edit point throws this :

```
Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 350, in run_
    return self.run(edit)
  File "./Edit History.py", line 163, in run
  File "./Edit History.py", line 63, in forward
  File "./Edit History.py", line 95, in next
IndexError: list index out of range
```

**Comment by Stuk** [comment]
Thanks, I'll look into it.

**Comment by Stuk** [comment]
I've added some asserts to the code to help in the future, but wasn't able to reproduce the error.

Do you have any steps that I can follow that cause this error to happen?

**Comment by franciscolourenco** [comment]
When it happens again I will try to narrow it down :)
